### ISSUE TITLE
Classes with Lombok annotations cause Apache NetBeans 12.2 to hang

### ISSUE THREAD

**Issue by cbm64chris** [junichi11/netbeans-rainbow-braces#11]
**Describe the bug**
When Rainbow-Braces is installed with the below configuration - a maven project with org.projectlombok-lombok-edge-SNAPSHOT annotations of classes cause NetBeans to hang when opening the file.

Product Version: Apache NetBeans IDE 12.2
Java: 15.0.1; OpenJDK 64-Bit Server VM 15.0.1+9
Runtime: OpenJDK Runtime Environment 15.0.1+9
System: Mac OS X version 10.16 running on x86_64; UTF-8; en_GB (nb)
User directory: /Users/cl011157/Library/Application Support/NetBeans/12.2
Cache directory: /Users/cl011157/Library/Caches/NetBeans/12.2

**To Reproduce**
1. Create a maven project with lombok-edge as a dependency
2. Create a class and include lombok annotations - such as @Data and @Builder(toBuilder = true)
3. Compile the project
4. Close the file
5. Restart NetBeans
6. Attempt to open the annotated class

**Expected behavior**
A title for the class will display but the editor will not display the contents. NetBeans will start to thrash on at least one core of the CPU. No actions will be possible, eventually macOS will report the application is not responding. The only resolution is to ForceQuit.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1 (BigSur)
 - NetBeans Version: 12.2
 - Plugin Version: 1.3.0

**Additional context**

**Comment by junichi11** [comment]
@cbm64chris Could you please attach an example project(as a zip file) to reproduce it?

**Comment by cbm64chris** [comment]
Hey @junichi11 I have actually just tried with another project and cannot recreate - but I can reproduce consistently with another (that I cannot share). There must be a conflict somewhere - I'll compile your plugin from source and get it into debug on my machine with the project that causes the issue to see if I can see what is happening. You can close this if you wish and I'll reopen if I can conclusively prove RainbowBraces is the culprit. Thanks Chris

**Comment by cbm64chris** [comment]
@junichi11 I have isolated the problem;

The hang will occur if 'Skip Comments' is enabled and the class has a comments, such as a licence, above the package declaration. It does not matter as previously reported if the class has any annotations. You can invoke the problem reliably by simply turning on, as is by default, 'Skip Comments' and type/paste above the package. NetBeans will begin to thrash and become unresponsive. I cannot see anything in the log that suggest why this happens and I have not looked at your implementation at this time.

Thanks
Chris

```
/**
 * Licence Header
 */
package com.rainbow.braces.test;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * LombokBuilder
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Builder(toBuilder = true)
public class LombokBuilder1 {
    private int myInt;
}
```

**Comment by junichi11** [comment]
@cbm64chris Reproducible. Thank you for investigating it.

**Comment by junichi11** [comment]
I found the cause. An infinite loop occurs. I'll fix it ASAP. Your instruction was helpful. Thank you!

**Comment by junichi11** [comment]
@cbm64chris Could you please verify it?
https://github.com/junichi11/netbeans-rainbow-braces/releases/tag/v1.3.0 (netbeans-rainbow-braces-1.3.0.1-dev.nbm)

If there is no problem, I'll upload it to the Plugin Portal as version 1.3.1.
Thanks.

**Comment by cbm64chris** [comment]
@junichi11 looks good, no issue found!

**Comment by junichi11** [comment]
@cbm64chris Thank you for your verification :) I'll add the new version to PP.
