### ISSUE TITLE
Possibly doesn't work for C/C++ project files (cpp,hpp,h,or c).

### ISSUE THREAD

**Issue by Lateralus138** [junichi11/netbeans-rainbow-braces#12]
**Describe the bug**

This doesn't seem to work for C/C++ project files (cpp,hpp,h,or c).

**To Reproduce**

1. Installed plugin
2. Set cpp,hpp,c, and h in Tools > Options > Miscellaneous > Rainbow: Mine-Types as per the README
3. Restarted Netbeans (just in case)

**Expected behavior**

Expected the brackets to be rainbow colored.

**Screenshots**

*C++* Here I realized cpp/hpp weren't valid Mime-Types and removed them and left c/h and it still isn't working.

![Screenshot_20220628_195059](https://user-images.githubusercontent.com/21045862/176331260-25bc5197-96c4-4297-ad5a-f3fe8580b5d1.png)

*Java*

![Screenshot_20220628_204314](https://user-images.githubusercontent.com/21045862/176333155-4e8334cf-5dba-403d-8c3b-77a3bee8848c.png)

**Desktop (please complete the following information):**

 - OS: Linux - Ubuntu 20.04.4 LTS
 - NetBeans Version: 14 - 8.2 Patch 2
 - Plugin Version: 1.3.1 - installed from NetBean IDE plugin tab

**Additional context**

I tested this with .java files and it works. I have reset all settings and themes to default and tested that way as well and it still doesn't seem to work. I thought maybe it's a specific issue with the C++ environment and settings and have tried to look through the settings that I can see and I can't find anything that relates (that I can tell).

New to NetBeans (though I've been a programmer a long time) so I'm not sure where to start to hunt down the problem myself.

**Comment by junichi11** [comment]
Maybe, they are not correct mime types.

See: `cnd.utils/src/org/netbeans/modules/cnd/utils/MIMENames.java`
```java
    /** Header */
    public static final String HEADER_MIME_TYPE = "text/x-h"; //NOI18N

    /** Preprocessor */
    public static final String PREPROC_MIME_TYPE = "text/x-cpp+preprocessor";// NOI18N

    /** any c/c++/header source file */
    public static final String SOURCES_MIME_TYPE = "text/x-cnd+sourcefile";// NOI18N
    
    /** Doxygen embedded */
    public static final String DOXYGEN_MIME_TYPE = "text/x-doxygen"; // NOI18N

    /** Double quoted string embedded */
    public static final String STRING_DOUBLE_MIME_TYPE = "text/x-cpp-string-double"; // NOI18N

    /** Single quoted string embedded */
    public static final String STRING_SINGLE_MIME_TYPE = "text/x-cpp-string-single"; // NOI18N

    /** C++ */
    public static final String CPLUSPLUS_MIME_TYPE = "text/x-c++"; //NOI18N

    /** C */
    public static final String C_MIME_TYPE = "text/x-c"; //NOI18N

```

**Comment by Lateralus138** [comment]
Alright, well after removing what I had and placing everything here and restarting NetBeans it's still not working for me:

![Screenshot_20220629_091758](https://user-images.githubusercontent.com/21045862/176459827-eb98531a-f0ec-43b5-a589-fb2384b74b56.png)

**Comment by Chris2011** [comment]
Unfortunately and I find this is wrong, the mimetype of a simple C/C++ file is text/X-c or text/X-c++ so with a capital x which we never had afaik. And text/x-c is in regex, if the plugin will not ignore cases, is not the same

![image](https://user-images.githubusercontent.com/795658/176461937-581f949b-8eff-4657-af50-e3c1417c3ca4.png)

So the regex, in your case, should be (x|X)-

![image](https://user-images.githubusercontent.com/795658/176462328-5cf885ec-c021-4715-b870-1e0f1d432a9f.png)

**Comment by junichi11** [comment]
@Lateralus138 Are you using cnd modules for NB 8.2? or you don't use it??

`c++` is not correct with regex.
If you using default c/c++ support, please add `X` as @Chris2011 wrote

i.e.
`^text/([xX]-)?(java|php5|javascript|json|css|less|sass|scss|c\+\+)$`

Your "Max number of lines" is `20`. See: https://github.com/junichi11/netbeans-rainbow-braces#max-number-of-lines

**Comment by Lateralus138** [comment]
I had fixed the max number of lines and the problem still persisted, but I figured it out: The `+` in the `c++` string had to be escaped throughout the regex and I should've known that, I've been doing regex for 27-28 years... :( Thanks for trying to help though and sorry for opening the thread.

![Screenshot_20220629_102436](https://user-images.githubusercontent.com/21045862/176475242-1dab085b-94d4-4768-b1fa-0ceff4b123aa.png)
