### ISSUE TITLE
make "adjacent" like braces less similar for default colors

### ISSUE THREAD

**Issue by alvint** [junichi11/netbeans-rainbow-braces#2]
In order for this plugin to be useful as well as whimsical, the colors of braces at adjacent levels should not be too similar, so you can easily tell at a glance what level each starting/closing brace corresponds to.

For example, below the colors of the two sets of parentheses are too similar to be useful to easily tell what level each one corresponds to:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/622202/46154879-0f983c80-c244-11e8-8411-4c482461fecd.png">

**Comment by alvint** [comment]
Now that I've actually read the instructions, it looks like you can customize the colors. Since many people may not read the instructions (what a world), I still suggest changing the default colors.

**Comment by Chris2011** [comment]
Yes, I changed the colors too, like red and light red. Of course maybe 9 Colors are not enough and for this you need nuances sooner or later.

**Comment by junichi11** [comment]
Just uncheck or change colors. 9 colors may too many.

**Comment by Chris2011** [comment]
Not for HTML/XML or scss where you have a lot of nested stuff in not so good code which is normal. I mean HTML/XML is not supported, I already created a ticket for that #1. Great plugin btw.

**Comment by junichi11** [comment]
I've adjusted the order a bit :)
https://github.com/junichi11/netbeans-rainbow-braces/releases/tag/v1.0.1
![netbeans-rainbow-braces-options](https://user-images.githubusercontent.com/738383/46181154-159f2380-c2ff-11e8-9853-be514e52ce84.png)
