### ISSUE TITLE
add support for .sql files

### ISSUE THREAD

**Issue by alvint** [junichi11/netbeans-rainbow-braces#3]
Currently, .sql files opened in the IDE aren't highlighted.

**Comment by Chris2011** [comment]
This is written in the readme, you can add SQL as a new mimetype in options.

**Comment by Chris2011** [comment]
Options -> Misc -> Rainbow. I added C/C++, HTML, by myself too.

**Comment by alvint** [comment]
Oh, now you expect me to be able to read?  :P
