### ISSUE TITLE
If I enable the rainbow plugin then my Xdebug cant toggle breakpoints.

### ISSUE THREAD

**Issue by sarelvdm** [junichi11/netbeans-rainbow-braces#7]
**Describe the bug**
Xdebug breakpoints cant be added if plugin rainbow braces  enabled 

***  Apache NetBeans IDE 11.0 
*** PHP version 7.3

**To Reproduce**
1. enable the netbeans rainbow braces under netbeans 11
2. cant add xdebug breakpoints to any line of code
3. disable rainbow braces.
4. restart netbeans.
5. Xdebug breakpoint working... 100%

**Comment by junichi11** [comment]
I know the following issue: https://issues.apache.org/jira/browse/NETBEANS-2610
Something for debugger may not work correctly.
Please try to open another file once, then select your first file tab again.

![nb-rainbow-braces-issue7](https://user-images.githubusercontent.com/738383/62859418-0880fc80-bd38-11e9-9632-85fca1e5de8e.png)

## My environment
Product Version: Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319)
Java: 1.8.0_202; Java HotSpot(TM) 64-Bit Server VM 25.202-b08
Runtime: Java(TM) SE Runtime Environment 1.8.0_202-b08
System: Linux version 4.16.0-041600-generic running on amd64; UTF-8;

**Comment by sarelvdm** [comment]
Hi, it is this issue...  https://issues.apache.org/jira/browse/NETBEANS-2610
Sorry, nothing wrong with your plugin,

thanks again.

**Comment by junichi11** [comment]
Need not to say sorry :) Will close this.
