### ISSUE TITLE
Poor performance on NB 11 and big .java file

### ISSUE THREAD

**Issue by agharta** [junichi11/netbeans-rainbow-braces#8]
**Describe the bug**
~4000 rows .java file: very poor performance

**To Reproduce**
1. Enable rainbow plugin (standard settings, default color scheme)
2. Open a .java file (many rows)
3. Try to edit, scroll, etc..
4. Very slow ide response. Hight cpu usage

**Expected behavior**
Editor should be smart to use.

**Screenshots**
NONE

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - NetBeans Version: 11.0
 - Plugin Version: 1.2.1

**Additional context**
NONE

**Comment by junichi11** [comment]
Yes, I know about it. I'll try to improve it when I can make time for it. If you use big files, please disable this plugin. Sorry for the inconvenience.

**Comment by agharta** [comment]
Hi,

No problem!

I'll wait for it!

My congratulations for this very useful plugin!

Best Regards,

Agharta


Il 22/08/19 11:45, Junichi Yamamoto ha scritto:

**Comment by konstantin-s** [comment]
> Yes, I know about it. I'll try to improve it when I can make time for it. **If you use big files**, please **disable** this plugin. Sorry for the inconvenience.

Same problem with large php files.

Can you add option for configure lines limit?
So plugin automatically can disabled for big file editing.

Thank you for your plugin and PHP supporting!

**Comment by junichi11** [comment]
I'm sorry I'm late. I've improved performance:

- Add the option for max lines
- Add the option for checking only visible area

![netbeans-rainbow-braces-options3](https://user-images.githubusercontent.com/738383/73281464-5e3c5900-4233-11ea-818d-9fd5c376c53b.png)


see: https://github.com/junichi11/netbeans-rainbow-braces/blob/nb110/README.md#max-number-of-lines

It would be nice if you test it with version 1.2.1.1-dev : https://github.com/junichi11/netbeans-rainbow-braces/releases/tag/v1.2.1 

Thanks.
